#!/bin/bash

# Version Bump Script for KACI Parental Control
# Usage: ./bump_version.sh <new_version> "<changelog_entry>"
# Example: ./bump_version.sh 0.2.4 "Fixed device selection bug"

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check arguments
if [ $# -lt 1 ]; then
    echo -e "${RED}Error: Version number required${NC}"
    echo "Usage: $0 <version> [changelog]"
    echo "Example: $0 0.2.4 'Fixed device selection bug'"
    exit 1
fi

NEW_VERSION="$1"
CHANGELOG="${2:-Version bump}"
BUILD_DATE=$(date +"%Y-%m-%d")
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

echo -e "${YELLOW}=== KACI Parental Control Version Bump ===${NC}"
echo "New Version: ${NEW_VERSION}"
echo "Changelog: ${CHANGELOG}"
echo "Build Date: ${BUILD_DATE}"
echo "Git Commit: ${GIT_COMMIT}"
echo ""

# Get current version from VERSION file
if [ -f "VERSION" ]; then
    CURRENT_VERSION=$(grep "CURRENT_VERSION=" VERSION | cut -d'=' -f2)
    echo "Current Version: ${CURRENT_VERSION}"
else
    echo -e "${RED}Error: VERSION file not found${NC}"
    exit 1
fi

# Confirm with user
read -p "Proceed with version bump? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
fi

echo -e "${GREEN}Updating version files...${NC}"

# 1. Update VERSION file
echo "  → VERSION"
sed -i '' "s/CURRENT_VERSION=.*/CURRENT_VERSION=${NEW_VERSION}/" VERSION
sed -i '' "s/BUILD_DATE=.*/BUILD_DATE=${BUILD_DATE}/" VERSION

# Add new changelog entry to VERSION file
sed -i '' "/# Version History:/a\\
# ${NEW_VERSION} - ${BUILD_DATE} - ${CHANGELOG}
" VERSION

# 2. Update parental_control.inc
echo "  → parental_control.inc"
sed -i '' "s/define('PC_VERSION', '.*');/define('PC_VERSION', '${NEW_VERSION}');/" parental_control.inc
sed -i '' "s/define('PC_BUILD_DATE', '.*');/define('PC_BUILD_DATE', '${BUILD_DATE}');/" parental_control.inc

# 3. Update parental_control.xml
echo "  → parental_control.xml"
sed -i '' "s|<version>.*</version>|<version>${NEW_VERSION}</version>|" parental_control.xml

# 4. Update info.xml
echo "  → info.xml"
sed -i '' "s|<version>.*</version>|<version>${NEW_VERSION}</version>|" info.xml

# 5. Update BUILD_INFO.json
echo "  → BUILD_INFO.json"
# Update build_info section
sed -i '' "s/\"version\": \".*\"/\"version\": \"${NEW_VERSION}\"/" BUILD_INFO.json
sed -i '' "s/\"build_date\": \".*\"/\"build_date\": \"${BUILD_TIMESTAMP}\"/" BUILD_INFO.json
sed -i '' "s/\"git_commit\": \".*\"/\"git_commit\": \"${GIT_COMMIT}\"/" BUILD_INFO.json

# Add changelog entry to BUILD_INFO.json (this is complex, let's create a temp file)
python3 - <<PYTHON_SCRIPT
import json
import sys

# Read BUILD_INFO.json
with open('BUILD_INFO.json', 'r') as f:
    data = json.load(f)

# Add new changelog entry at the beginning
new_entry = {
    "version": "${NEW_VERSION}",
    "date": "${BUILD_DATE}",
    "type": "update",
    "changes": ["${CHANGELOG}"]
}

if 'changelog' not in data:
    data['changelog'] = []

data['changelog'].insert(0, new_entry)

# Write back
with open('BUILD_INFO.json', 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')

print("  → BUILD_INFO.json changelog updated")
PYTHON_SCRIPT

echo ""
echo -e "${GREEN}✅ Version bumped to ${NEW_VERSION}${NC}"
echo ""
echo "Files updated:"
echo "  - VERSION"
echo "  - parental_control.inc"
echo "  - parental_control.xml"
echo "  - info.xml"
echo "  - BUILD_INFO.json"
echo ""

# Ask if user wants to commit
read -p "Commit these changes? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    git add VERSION parental_control.inc parental_control.xml info.xml BUILD_INFO.json
    git commit -m "chore: Bump version to ${NEW_VERSION}

${CHANGELOG}

Auto-generated by bump_version.sh"
    echo -e "${GREEN}✅ Changes committed${NC}"
    echo ""
    read -p "Push to GitHub? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git push origin main
        echo -e "${GREEN}✅ Pushed to GitHub${NC}"
    fi
else
    echo "Files staged but not committed. Review changes and commit manually."
fi

echo ""
echo -e "${GREEN}Done!${NC}"

